dist: xenial
sudo: required
language: generic
before_install:
  - sudo apt-get install -y --allow-unauthenticated gcc-multilib qemu
  - sudo ln -s qemu-system-x86_64 /usr/bin/qemu
install:
  - make
script:
  - ./grade-lab1
